services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: "alagalink-web:latest"
    user: "${UID:-1000}:${GID:-1000}"
    env_file:
      - .env
    environment:
      - HOME=/home/developer
    ports:
      - "8000:80"
      - "5173:5173"
    networks:
      - db_network
      - mailtrap_network
    volumes:
      - ./_setup/web_scripts:/scripts
      - ./src:/var/www/html
      - ./docker_home:/home/developer    # HOME for npm & node
      - ./storage:/var/www/html/storage
      - ./logs:/var/www/html/storage/logs
    depends_on:
      db:
        condition: service_healthy
      mailtrap:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 5
    command: >
      bash -c "
      mkdir -p /home/developer/.npm &&
      dos2unix /scripts/* &&
      chmod +x /scripts/* &&
      /scripts/init.sh &&
      php artisan config:cache &&
      apache2-foreground"

  db:
    image: "postgres:18"
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    networks:
      - db_network
    volumes:
      - pg_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -h localhost -U \"$POSTGRES_USER\" -d \"$POSTGRES_DB\""]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  mailtrap:
    image: axllent/mailpit:latest
    user: "${UID:-1000}:${GID:-1000}"   # Make sure files are created with host user
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - mailtrap_network
    volumes:
      - ./mailtrap_data:/data
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /data/mailpit.db
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1
    restart: unless-stopped

networks:
  db_network:
  mailtrap_network:

volumes:
  pg_data: