
import { LostReport } from '../../types';

export const MOCK_MISSING: LostReport[] = [
  {
    id: 'r-1',
    userId: 'LT-PWD-1005',
    name: 'Ronel Olsim',
    reporterId: 'LT-PWD-1000',
    timeMissing: new Date(Date.now() - 36 * 60 * 60 * 1000).toISOString(),
    lastSeen: 'Km. 5 Public Market',
    description: 'Wearing a traditional woven vest.',
    clothes: 'Woven vest, Denim jeans',
    height: '5\'4"',
    bodyType: 'Slim',
    dissemination: { radio: true, socialMedia: true, context: 'Last seen near vegetable trading post.' },
    status: 'Missing',
    isPosted: true,
    photoUrl: 'https://randomuser.me/api/portraits/men/4.jpg',
    missingNarrative: { what: 'Missing from market', when: '2 days ago', why: 'Separated from guardian', how: 'Left without supervision' }
  },
  {
    id: 'r-4',
    userId: 'LT-PWD-1008',
    name: 'Maria Santos',
    reporterId: 'LT-PWD-1001',
    timeMissing: new Date(Date.now() - 48 * 60 * 60 * 1000).toISOString(),
    lastSeen: 'St. Joseph School Area',
    description: 'Female with hearing impairment, last seen wearing pink school uniform.',
    clothes: 'Pink school uniform, white sneakers',
    height: '5\'1"',
    bodyType: 'Average',
    dissemination: { radio: true, socialMedia: true, context: 'Left school without informing teachers. Intellectual disability.' },
    status: 'Missing',
    isPosted: true,
    photoUrl: 'https://randomuser.me/api/portraits/women/5.jpg',
    missingNarrative: { what: 'Missing from school', when: '2 days ago', why: 'Wandered off during break', how: 'Did not return to classroom' }
  },
  {
    id: 'r-5',
    userId: 'LT-PWD-1009',
    name: 'Juan dela Cruz',
    reporterId: 'LT-PWD-1002',
    timeMissing: new Date(Date.now() - 60 * 60 * 60 * 1000).toISOString(),
    lastSeen: 'La Trinidad Public Hospital',
    description: 'Male with autism spectrum disorder, non-verbal communication.',
    clothes: 'Blue jacket, black pants, red cap',
    height: '5\'7"',
    bodyType: 'Athletic',
    dissemination: { radio: true, socialMedia: true, context: 'Discharged but did not return home. High-support needs.' },
    status: 'Missing',
    isPosted: true,
    photoUrl: 'https://randomuser.me/api/portraits/men/8.jpg',
    missingNarrative: { what: 'Missing after hospital discharge', when: '2.5 days ago', why: 'Became disoriented', how: 'Left premises without guardian supervision' }
  },
  {
    id: 'r-6',
    userId: 'LT-PWD-1010',
    name: 'Rosa Fernandez',
    reporterId: 'LT-PWD-1003',
    timeMissing: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    lastSeen: 'City Government Center',
    description: 'Senior citizen with visual impairment and dementia.',
    clothes: 'Beige cardigan, gray pants, walking cane',
    height: '5\'0"',
    bodyType: 'Petite',
    dissemination: { radio: true, socialMedia: true, context: 'Last seen at DSWD office. Memory issues. Multiple disabilities.' },
    status: 'Missing',
    isPosted: true,
    photoUrl: 'https://randomuser.me/api/portraits/women/12.jpg',
    missingNarrative: { what: 'Missing from government office', when: '3 days ago', why: 'Cognitive impairment', how: 'Wandered from office during service hours' }
  },
  {
    id: 'r-7',
    userId: 'LT-PWD-1011',
    name: 'Pedro Reyes',
    reporterId: 'LT-PWD-1004',
    timeMissing: new Date(Date.now() - 84 * 60 * 60 * 1000).toISOString(),
    lastSeen: 'Barangay Health Center',
    description: 'Male with severe orthopedic impairment, uses wheelchair.',
    clothes: 'White t-shirt, brown shorts',
    height: '5\'5"',
    bodyType: 'Slim',
    dissemination: { radio: true, socialMedia: true, context: 'Left medical appointment. Wheelchair-dependent. Recent behavioral changes.' },
    status: 'Missing',
    isPosted: true,
    photoUrl: 'https://randomuser.me/api/portraits/men/15.jpg',
    missingNarrative: { what: 'Missing from health center', when: '3.5 days ago', why: 'Emotional disturbance triggered', how: 'Left in wheelchair during follow-up visit' }
  }
];
