
import { UserProfile, DisabilityCategory } from '../types';

export const MOCK_ADMINS: UserProfile[] = [
  {
    id: `ADM-LT-1001`,
    email: "joe.kising@alagalink.ph",
    password: 'password',
    role: 'SuperAdmin',
    firstName: "Joe",
    middleName: "B.",
    lastName: "Kis-ing",
    address: `Km. 5, La Trinidad, Benguet`,
    birthDate: `1985-06-15`,
    provincialAddress: 'Benguet',
    civilStatus: 'Married',
    occupation: 'PDAO Administrator',
    sex: 'Male',
    bloodType: 'O+',
    age: 38,
    contactNumber: `09171234567`,
    disabilityCategory: DisabilityCategory.None,
    familyComposition: [],
    emergencyContact: { 
      name: 'PDAO Emergency Services', 
      relation: 'Office', 
      contact: '0911-222-3333' 
    },
    professionalQualifications: {
      citizenship: 'Filipino',
      residency: 'La Trinidad',
      education: 'Bachelor of Science in Social Work',
      eligibility: 'Career Service Professional / Registered Social Worker',
      trainingHours: 120,
      experienceYears: 12,
      licenseNumber: 'PRC-RSW-0092831',
      isSocialWorker: true
    },
    registrantType: 'PDAO Staff',
    status: 'Active',
    photoUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
    customData: {},
    history: { lostAndFound: [], programs: [] }
  },
  {
    id: `ADM-LT-1002`,
    email: "cynthia.cabigat@alagalink.ph",
    password: 'password',
    role: 'Admin',
    firstName: "Cynthia",
    middleName: "P.",
    lastName: "Cabigat",
    address: `Poblacion, La Trinidad, Benguet`,
    birthDate: `1990-03-22`,
    provincialAddress: 'Benguet',
    civilStatus: 'Single',
    occupation: 'Social Worker',
    sex: 'Female',
    bloodType: 'A+',
    age: 33,
    contactNumber: `09170000001`,
    disabilityCategory: DisabilityCategory.None,
    familyComposition: [],
    emergencyContact: { name: 'Staff Support', relation: 'Office', contact: '0911-000-0001' },
    professionalQualifications: {
      citizenship: 'Filipino',
      residency: 'La Trinidad',
      education: 'Bachelor of Science in Psychology',
      eligibility: 'Career Service Professional',
      trainingHours: 48,
      experienceYears: 5,
      licenseNumber: 'PRC-PSY-0021312',
      isSocialWorker: false
    },
    registrantType: 'PDAO Staff',
    status: 'Active',
    photoUrl: 'https://randomuser.me/api/portraits/women/44.jpg',
    customData: {},
    history: { lostAndFound: [], programs: [] }
  },
  {
    id: `ADM-LT-1003`,
    email: "nikki.ibayan@alagalink.ph",
    password: 'password',
    role: 'Admin',
    firstName: "Nikki Rose",
    middleName: "B.",
    lastName: "Ibayan",
    address: `Pico, La Trinidad, Benguet`,
    birthDate: `1992-11-05`,
    provincialAddress: 'Benguet',
    civilStatus: 'Single',
    occupation: 'Clerk',
    sex: 'Female',
    bloodType: 'B+',
    age: 31,
    contactNumber: `09170000002`,
    disabilityCategory: DisabilityCategory.None,
    familyComposition: [],
    emergencyContact: { name: 'Staff Support', relation: 'Office', contact: '0911-000-0002' },
    professionalQualifications: {
      citizenship: 'Filipino',
      residency: 'La Trinidad',
      education: 'BS in Public Administration',
      eligibility: 'Career Service Sub-Professional',
      trainingHours: 32,
      experienceYears: 3,
      isSocialWorker: false
    },
    registrantType: 'PDAO Staff',
    status: 'Active',
    photoUrl: 'https://randomuser.me/api/portraits/women/12.jpg',
    customData: {},
    history: { lostAndFound: [], programs: [] }
  },
  {
    id: `ADM-LT-1004`,
    email: "kenneth.wallac@alagalink.ph",
    password: 'password',
    role: 'Admin',
    firstName: "Kenneth",
    lastName: "Wallac",
    address: `Wangal, La Trinidad, Benguet`,
    birthDate: `1988-08-15`,
    provincialAddress: 'Benguet',
    civilStatus: 'Married',
    occupation: 'Technician',
    sex: 'Male',
    bloodType: 'O-',
    age: 35,
    contactNumber: `09170000003`,
    disabilityCategory: DisabilityCategory.None,
    familyComposition: [],
    emergencyContact: { name: 'Staff Support', relation: 'Office', contact: '0911-000-0003' },
    professionalQualifications: {
      citizenship: 'Filipino',
      residency: 'La Trinidad',
      education: 'BS Information Technology',
      eligibility: 'Career Service Professional',
      trainingHours: 24,
      experienceYears: 7,
      isSocialWorker: false
    },
    registrantType: 'PDAO Staff',
    status: 'Active',
    photoUrl: 'https://randomuser.me/api/portraits/men/55.jpg',
    customData: {},
    history: { lostAndFound: [], programs: [] }
  }
];
